name: 🧹 Lint the codebase

on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - 'gh-readonly-queue/**'
  merge_group:

jobs:
  check_changes:
    name: Check if code files changed
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.changes.outputs.source_code }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            source_code:
              - 'lib/**'
              - 'include/**'
              - 'tools/**'

  run_clang-format:
    name: Lint the codebase with clang-format
    needs: check_changes
    if: needs.check_changes.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'lib'
          - 'include'
          - 'tools'
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/ programs
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '20'
          check-path: ${{ matrix.path }}

  lint_summary:
    name: Lint Summary
    runs-on: ubuntu-latest
    needs: [check_changes, run_clang-format]
    if: always()
    steps:
      - name: Check lint results
        run: |
          if [[ "${{ needs.check_changes.outputs.code_changed }}" == "false" ]]; then
            echo "✅ No code changes detected, skipping lint checks"
            exit 0
          elif [[ "${{ needs.run_clang-format.result }}" == "success" ]]; then
            echo "✅ All lint checks passed"
            exit 0
          else
            echo "❌ Lint checks failed"
            exit 1
          fi
